### ISSUE TITLE
The second part of the tutorial?

### ISSUE THREAD

**Issue by lfaller** [shearer/simboot#1]
Hi all,

I am very interested in calculating confidence intervals for the Shannon indexes for metagenomics data. Do you have any advice on a "best-practices" workflow using the simboot packages following an analysis with phyloseq? Are the diversity measures calculated for individual subjects' samples and then averaged together? And it is for this average that I need to estimate CIs?

Thanks a bunch!
~Lina

**Comment by shearer** [comment]
Hi Lina,

I am very sorry, but I saw your question to late. Are you already interested in the CIs?

Bests
Ralph

**Comment by lfaller** [comment]
Hi Ralph,

Yes, I am interested in CIs, but I think I was able to figure it out!

Best,
~Lina

**Comment by shearer** [comment]
Fine! If questions arise, please ask.

Am 1. August 2016 3:48:57 nachm. schrieb lfaller notifications@github.com:
